### ISSUE TITLE
Custom Trash can reaction to replace red X

### ISSUE THREAD

**Issue by eivl** [python-discord/bot#514] opened 2019-10-11 20:47 UTC
[org-issue-141](https://github.com/python-discord/organisation/issues/141) talks about how certain members are confused about the red X that is added to embeds. 
Like the one that !eval uses
![eval output](https://i.imgur.com/pdSimjS.png)

The consensus is that we change it for a nice trashcan 🗑

**Comment by MarkKoz** [comment] 2019-10-11 20:49
Ideally we'd have a custom emote that resembles a trash can, but looks nicer than twemoji's.

**Comment by Numerlor** [comment] 2019-10-11 20:59
I was thinking something like this with simpler lines would look good
![](https://www.shareicon.net/data/48x48/2016/10/11/842408_trash_512x512.png)

**Comment by lemonsaurus** [comment] 2019-10-11 21:00
yeah, I was also thinking something like that @Numerlor

**Comment by kraktus** [comment] 2019-10-12 16:26
Duplicate of #297

**Comment by scragly** [comment] 2019-11-15 12:05
Closing due to duplicate.

**Closed by scragly** 2019-11-15 12:05 UTC
Labels: area: Frontend, type: Enhancement
