### ISSUE TITLE
Add a !mypy command

### ISSUE THREAD

**Issue by ionite34** [python-discord/bot#2368] opened 2022-12-22 04:29 UTC
## Proposal to add a `!mypy` command

Works like `!eval` or `!timeit` but instead of running the file, run a mypy type check on the file using snekbox and return the stdout results.

Discussions on mypy results and inferrable types are pretty common, and usually means copying the output of mypy to paste with code in a discussion, having a command would encourage reproducible examples (like eval does)

## Depends on
- https://github.com/python-discord/snekbox/pull/159
- https://github.com/python-discord/bot/pull/2326
- Add `mypy` to our snekbox deployment venv

**Comment by wookie184** [comment] 2022-12-22 13:50
Related: #1880

**Comment by ionite34** [comment] 2022-12-23 01:31
> Related: #1880

Hm, do you think we should just give a way for users to specify a `-m`? That would allow stuff like `mypy` and `flake8` without adding new commands. It would just need for those modules to be added to snekbox.

```py
!e -m mypy
# code to check with mypy
```

```py
!e -m flake8
# code to check with mypy
```

we can continue to default the first block as `main.py` and append `main.py` to the end of the arguments

**Comment by wookie184** [comment] 2022-12-29 14:48
Dedicated commands would make it easier to add special casing to commands, which we may need (e.g. to provide default settings, maybe allow users to change settings, and maybe for formatting the output).

Commands are more "standard" so e.g. they would work with the `!help` command by default.

**Comment by wookie184** [comment] 2024-04-19 17:59
Closing as a duplicate of https://github.com/python-discord/bot/issues/1880, since it's still not approved I think it makes sense to keep discussion in once place.

**Closed by wookie184** 2024-04-19 17:59 UTC
