### ISSUE TITLE
Delete Message API change breaks bot features

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/bot#738] opened 2020-02-04 21:58 UTC
Recently, the deleted messages API received an update that introduced a new required field (`attachments`). Unfortunately, not every bot feature using this endpoint has been updated yet, causing the API to reject the requests. 

One such feature that currently fails is bulk deletion by [the Clean cog](https://github.com/python-discord/bot/blob/master/bot/cogs/clean.py). Another one is part of [the on_message_delete event listener in the modlog Cog](https://github.com/python-discord/bot/blob/master/bot/cogs/moderation/modlog.py#L577). We should probably do a thorough check to see if there are more features that rely on this endpoint.

The fix should be straightforward, as we only need to send along an empty list for the `attachments` field to make it work.

**Comment by MarkKoz** [comment] 2020-03-14 23:03
Duplicate of #792.

**Closed by MarkKoz** 2020-03-14 23:03 UTC
Labels: area: API, priority: 1 - high, type: bug
