### ISSUE TITLE
New tag request

### ISSUE THREAD

**Issue by Diabolical5777** [python-discord/bot#1723] opened 2021-08-05 20:17 UTC
**Description:**
The tag informs why YouTube or any tutorials are not good to be followed. 

**Motivation:**
There are a lot of users asking for help on code that they were spoonfeeded or simply do not understand and I think this is a good way to tell them to stop and try and understand since all information you want about making a command can be found in docs.

**Tag content: (can of course be shortened since this is fairly long)**
Tutorials are fundamentally flawed in concept when it comes to teaching you something like a programming language. The simple reason for this is a programming language is how you create whatever you want, a tutorial is something that teaches you how to do what the tutorial is teaching. 
I recommend reading through all of these points if you want to understand why
A couple of points against tutorials...especially video tutorials: 
- Tutorials teach you how to create a project, a specific program, a specific script, etc. This causes many many people to only know how to do this one specific thing. 
- A programming language is an entire language itself, this is obvious in of itself but for this point think of this compared to a real language...people have accents, there's multiple ways to say the same thing, there's multiple pronunciations for some words. This same kind of concept applies to programming languages, there are many ways to achieve the same thing, there are code styles which people pick up from learning. Sometimes...these practices can be bad and if you're just learning, how would you know if the tutorial is using some bad practice? Trust me...this happens a lot 
- Tutorials are made for that specific version of whatever it's using...whether this be python, the discord.py library, some other library it's using...etc. As time goes on that can very quickly become outdated
- Sometimes there are "advanced" or hard concepts that are covered in a tutorial, you're not guaranteed to understand all of it right off the bat. It is extremely hard to provide the relevant documentation for every single concept covered....there would be so much. 
- Specifically for this library, the people who look for tutorials are typically new to the language...this library is not meant for beginners, there are some advanced concepts (example asyncio) that are covered, and jumping straight into that as a beginner is very bad.

**Comment by spyoungtech** [comment] 2021-08-05 21:49
Closing as duplicate of #1722

**Closed by spyoungtech** 2021-08-05 21:49 UTC
