### ISSUE TITLE
!e Command won't work if codeblock is right after

### ISSUE THREAD

**Issue by aydaultani** [python-discord/bot#2047] opened 2022-01-14 12:47 UTC
# Problem

![image](https://i.imgur.com/coZu8UY.png)

The code in the above image wont execute

![image](https://i.imgur.com/AvSCGbk.png)

The code in the above image will execute

**Comment by ToxicKidz** [comment] 2022-01-14 13:23
The `!e` command, as well as every other command, needs a space after the command so the bot can actually know what the command is. We *can* workaround this, but I'm not sure if it's worth it.

**Comment by arnavthedumbass** [comment] 2022-01-14 17:11
That makes sense but it was baffling at first when my command didn't work just in a random OT convo. It might not be worth it but it's one of those things that's good to have in certain situations.

**Comment by DMFriends** [comment] 2022-01-14 17:59
Yeah I agree with @pedro-anthony

**Comment by arnavthedumbass** [comment] 2022-01-14 18:57
> Yeah I agree with @pedro-anthony 

Alright, my only concern was again for it to be a thing that's just good

**Comment by wookie184** [comment] 2022-01-14 21:32
> I really don't see why it should be bothered to hijack the commands extension to workaround this "issue". Merely adding a space after your command is effortless.

The issue is not so much that adding a space is too much effort, but to the user it could be unclear why the bot didn't respond.

As the discord client renders with and without a space the same, two seemingly equal invocations can have different results. This _is_ sort of confusing and comes up every now and again with someone wondering why their command isn't working.

That said, this is still minor. I do wonder what implementing this would require though, as if it's fairly simple it could be alright.

**Comment by HassanAbouelela** [comment] 2022-01-14 21:59
The easiest “fix” would be adding a command alias which is `eval<tick><tick><tick>` (and another for the `e` alias). This is quite ugly though, and will require extra work in terms of modifying the code parsing logic to handle the now missing opening quotes

**Comment by wookie184** [comment] 2022-01-14 22:10
> The easiest “fix” would be adding a command alias which is `eval<tick><tick><tick>` (and another for the `e` alias). This is quite ugly though, and will require extra work in terms of modifying the code parsing logic to handle the now missing opening quotes

That would also need to include the language, right? So probably wouldn't be too feasible, yeah

**Comment by pedro-anthony** [comment] 2022-01-15 01:29
> > I really don't see why it should be bothered to hijack the commands extension to workaround this "issue". Merely adding a space after your command is effortless.
> 
> The issue is not so much that adding a space is too much effort, but to the user it could be unclear why the bot didn't respond.
> 
> As the discord client renders with and without a space the same, two seemingly equal invocations can have different results. This _is_ sort of confusing and comes up every now and again with someone wondering why their command isn't working.
> 
> That said, this is still minor. I do wonder what implementing this would require though, as if it's fairly simple it could be alright.

Ah, most certainly. I see how this could be an issue now.

**Comment by ShakyaMajumdar** [comment] 2022-01-15 03:42
@wookie184 If there was an alias for !e```, wouldn't fuzzy matching be able to handle the language bit?

**Comment by onerandomusername** [comment] 2022-01-15 03:48
> @wookie184 If there was an alias for !e```, wouldn't fuzzy matching be able to handle the language bit?

No, it wouldn't work because the codeblock parser wouldn't receive the first three \`\`\` which would mean that the regex that detects \` would be thrown off.

**Comment by HassanAbouelela** [comment] 2022-01-15 04:25
It wouldn’t work no, we don’t do fuzzy matching like that. The fuzzy matching for command names only sends a message listing similar commands. You’d have to add all aliases no matter what (6 by my count if you add python and py). It’ll also look quite ugly in the help list if we did the command approach.

We could do it in the error handler and match the first portion of the invocation command, but I don’t think we should go beyond sending an error message. Trying to adjust the parsing to account for this case is more work than it’s worth.

**Comment by onerandomusername** [comment] 2022-01-15 04:35
> Right, but that's not what I was talking about

Let me explain.

Scale's concerns about needing to modify the parser are valid, based on the below.

> I think wookie's point was that even if !e\`\`\`​ was a command, !e‍\`\`\`py wouldn't work because of the py. I'm saying it could work because of fuzzy matching

We don't have any fuzzy matching on command names, only on tags. Additionally, we can show this behavior on the current bot by running the command without the first three ```, as adding an alias would mean that these three ticks would not be sent to the command, if there were no spaces.
![image](https://user-images.githubusercontent.com/71233171/149608328-7df4d5a2-7c68-4a33-a40d-b74acf08c021.png)

The [existing parser](https://github.com/python-discord/bot/blob/26c5587ac13e5414361bb6e7ada42983b81014d2/bot/exts/utils/snekbox.py#L75-L103) doesn't match any codeblock in the contents because the second ``` does not exist.

However, one way to ensure the command is executed would be to override [`bot.process_commands`](https://github.com/Rapptz/discord.py/blob/45d498c1b76deaf3b394d17ccf56112fa691d160/discord/ext/commands/bot.py#L904-L977) and implementing a split after the `
Whether this solution is viable, I'm not sure, but it does exist and would be a possible method to consider overriding.

------
Note after writing: Huh, another possible and easier solution may be a tag named `eval`` which would likely trigger on fuzzy matching when a user did not use the correct eval command... food for thought.

**Comment by arnavthedumbass** [comment] 2022-01-15 07:57
I'm not quoting like 4 people but I'm glad to see someone come up with the point of the user being confused as to why the bot didn't respond. 

Cheers,
Arnav

**Comment by Qwerty-133** [comment] 2022-01-21 12:15
We could run a regex upon getting a `CommandNotFound` exception to determine if `!eval` or `!e` is followed by a back-tick, and if so, add a space in between. We could then just process the command again.

**Comment by arnavthedumbass** [comment] 2022-02-03 17:05
Closing

**Comment by DMFriends** [comment] 2022-05-27 11:07
> Looks like it was reopened! Good to know 

@aydaultani Yep, and that's because someone brought up the issue again on the Discord server: https://discord.com/channels/267624335836053506/635950537262759947/979496425983471626

**Comment by aydaultani** [comment] 2022-05-27 14:50
> > Looks like it was reopened! Good to know 
> 
> @aydaultani Yep, and that's because someone brought up the issue again on the Discord server: https://discord.com/channels/267624335836053506/635950537262759947/979496425983471626

Ahaha That's amazing, well we better get working on a fix then!

**Comment by wookie184** [comment] 2022-05-27 17:45
What I have currently, based on @Qwerty-133's idea. I think this probably the neatest way, given we already have some custom behaviour here.
```diff
--- a/bot/exts/backend/error_handler.py
+++ b/bot/exts/backend/error_handler.py
@@ -65,7 +65,11 @@ class ErrorHandler(Cog):
         if isinstance(e, errors.CommandNotFound) and not getattr(ctx, "invoked_from_error_handler", False):
             if await self.try_silence(ctx):
                 return
-            await self.try_get_tag(ctx)  # Try to look for a tag with the command's name
+            # Try to look for a tag with the command's name
+            if await self.try_get_tag(ctx):
+                return
+            await self.try_run_eval(ctx)
+
         elif isinstance(e, errors.UserInputError):
             log.debug(debug_message)
             await self.handle_user_input_error(ctx, e)
@@ -179,6 +183,18 @@ class ErrorHandler(Cog):
         if not any(role.id in MODERATION_ROLES for role in ctx.author.roles):
             await self.send_command_suggestion(ctx, ctx.invoked_with)

+    async def try_run_eval(self, ctx: Context) -> None:
+        eval = self.bot.get_command("eval")
+        ctx.invoked_from_error_handler = True
+        
+        intended_command = ctx.invoked_with.split("```", maxsplit=1)[0]
+        if not self.bot.get_command(intended_command) == eval:
+            return
+
+        command, sep, end = ctx.message.content.partition("```")
+        ctx.message.content = command + " " + sep + end
+        await self.bot.process_commands(ctx.message)
+
     async def send_command_suggestion(self, ctx: Context, command_name: str) -> None:
         """Sends user similar commands if any can be found."""
         # No similar tag found, or tag on cooldown -
```

**Closed** 2022-05-29 12:02 UTC

**Comment by aydaultani** [comment] 2022-05-29 13:30
👍
