### ISSUE TITLE
Tag: dont-ask-to-ask

### ISSUE THREAD

**Issue by Objectivitix** [python-discord/bot#1592] opened 2021-05-17 13:08 UTC
## Description
This will be a tag that briefly explains why "asking if one could ask a question"/"asking if there's anyone who can answer a question" or any other variants decreases one's chance of getting an answer quickly.

## Motivation
Currently there is a [website](https://dontasktoask.com/) that explains this but it is too long and considered dismissive (or sometimes used in a passive-aggressive way), because 1) people would have to navigate between the site and server and 2) the wording of the website is... not that great for people who really just **DON'T KNOW**. (e.g. "..which is just lazy. If you're not willing to do the work to solve your problem, why should we?")

However, this means we'll have to manually type out and explain each time why people shouldn't ask to ask.

Hence, I believe rewording it a bit, make it sound friendlier, and packaging it in a nice tag would be the best solution.

**Comment by HassanAbouelela** [comment] 2021-05-17 13:14
Duplicate of #1111. That issue also explained why the original ask tag failed, and from what I gather, this suggestion is no different from the original tag or the website. The third reason the website was blocked, the reason you didn't mention, is that people would *use* it in a dismissive way, and no amount of content changes can fix that. We've discussed this hundreds of times, but every time we come to the same conclusion that something like this just won't work.

**Comment by ChrisLovering** [comment] 2021-05-17 13:15
I'm extremely against this type of tag. Users who this tag would be used for are usually newer users, and if one of their first interactions with our server is our members sending this tag to them with no other context could be very off putting.

I would much prefer our members to just write out a sentence asking them what their question is, as that would be far more welcoming.

**Comment by HassanAbouelela** [comment] 2021-05-17 13:16
I'll close this now. If you really wish, you're welcome to comment on the issue I linked, but I think you should at least talk about this idea on server before you move on. We can point you towards older discussions, and tell you about all the ideas that were considered before hand, and dismissed.

**Closed by HassanAbouelela** 2021-05-17 13:16 UTC

**Comment by Objectivitix** [comment] 2021-05-17 13:32
Got it @HassanAbouelela and @ChrisLovering. Thank you all for telling me this, and sorry I didn't know I'd have to discuss in the server first before opening an issue (I thought issue was the first step).
