### ISSUE TITLE
Migrate to slash commands

### ISSUE THREAD

**Issue by ddjerqq** [python-discord/bot#2362] opened 2022-12-09 23:10 UTC
I think we should start migrating to slash commands. 
It will especially be useful for commands like `!d` and `!rule`, other than those, there are many cool commands which the server's users may not even know of, for example: `!listcomp` or ;) `!or` and so on. I think if we migrated to slash commands and added autofill for some commands, it would really help people who are helping others to pull up examples faster.

Many times, I had the issue of not knowing the exact command, for `!list-comp` or `!list-comprehension` or `!listcomp` and that was quite annoying, if we have some kind of completions for the commands, the community could profit, in time, and ease of use of the bot.

disnake server has an amazing command for this:
![image](https://user-images.githubusercontent.com/57017344/206809972-26253c28-b743-48d5-a653-52cd398afa8c.png)

**Comment by Thornily** [comment] 2022-12-10 16:32
Well this would be cool, I believe with the commands `!rule` and `!d` it would be too cluttered (especially on mobile) and it would be easier to leave it as is. 

>  there are many cool commands which the server's users may not even know of, for example: !listcomp or ;) !or

Thats why there is a `!tags` command, although I do agree they are still hidden.

Would love to continue this discussion, if you have any more ideas.

**Comment by ddjerqq** [comment] 2022-12-11 17:08
I am going to be honest, I've been on the server for quite a long time now and I've never seen the `!tags` command, only now, once you've told me it exists, did I check it out. That command is very useful indeed to remember all the tags and give people formatted, clean, pretty descriptions to poythonic or general computer topics.

Though I still think the community would gain more from slash commands than suffer from the clutter on mobiles. Without a doubt the discord slash command view is terrible on mobile, nevertheless, I think the server is constantly evolving, from ticket-like channel help system to forum pages, from event to event to server is quickly evolving and adapting to changes, so it's really puzzling when there are no slash commands on the server yet.

I think the main benefits of slash commands would be to allow the users of the server to view all the commands that are available at their screen's reach, without having to dig through the source code here or go through any other troubles. Just my opinion tho

**Comment by Robin5605** [comment] 2022-12-26 02:27
We've already begun a slow but steady migration to using the new features. We already have a bunch of buttons in places, and we're about to start using context menus for bookmarks. Our approach to all of these is to create these new slash commands as alternatives, while keeping the text commands as they are. People can use whichever they prefer the most. I am completely in favor of creating these alternative slash commands for commands that would benefit from them (not all commands do, it's important to keep that in mind).

**Comment by Robin5605** [comment] 2022-12-26 02:27
Oh, and this would probably have to be a whole project on it's own as we have quite a few commands and migrating to slash commands would be a lot of work.

**Comment by wookie184** [comment] 2022-12-29 14:58
Duplicate of #2188, will close that one since this has more discussion, but please check for existing issues before opening a new one in the future.

**Comment by ChrisLovering** [comment] 2023-02-05 22:14
While I agree most of our commands could work as slash commands, I do not believe one mega-issue is the best approach for migrating.

Instead I'd suggest raiding raising an issue on a per-command basis, describing the benefit of migrating it to a slash command, and a proposed implementation. Each issue can then be separately approved by a core dev when appropriate.

**Closed by ChrisLovering** 2023-02-05 22:14 UTC
