### ISSUE TITLE
Migrating !tag to slash commands

### ISSUE THREAD

**Issue by Canttuchdiz** [python-discord/bot#2394] opened 2023-02-01 15:50 UTC
Migrating **!tag** to a slash command. Allowing for autocomplete, and a subcommand **/tag help** or **/tags** listing all tags. That list could also be ephemeral, so the user can see all the tags. Also, if possible, make the main command **/tag**, and the param would be autocomplete.

**Comment by JacobCoffee** [comment] 2023-02-05 22:06
I believe this is a duplicate of #2362

**Comment by ChrisLovering** [comment] 2023-02-05 22:17
> I believe this is a duplicate of #2362

I suggested splitting out the issue in this way, see my recent comment in the issue for context.

> and a subcommand /tag help or /tags listing all tags. That list could also be ephemeral, so the user can see all the tags.

We could make the tag name argument optional, so if not given it lists all the tags in a paginated embed, like it does currently.

> Also, if possible, make the main command /tag, and the param would be autocomplete.

I agree with this, we should use fuzzy matching for auto complete logic, similar to the current tag suggestion autocomplete, so that users can use the same short-hand names for tags as they currently do.

**Comment by Ibrahim2750mi** [comment] 2023-02-13 20:43
can I be assigned this?

**Comment by Ibrahim2750mi** [comment] 2023-02-13 21:35
Also the reactions on the embed needs to be changed to buttons right?
![2023-02-14_03-03](https://user-images.githubusercontent.com/74553450/218579591-c7f4fd95-91f0-409c-ae27-6879914fda4d.png)

**Comment by wookie184** [comment] 2023-02-21 18:28
I'm not sure if the intention of this issue is to replace the direct invocation of tags (e.g. through `!code`), or just the actual `!tag` command.

I think replacing the actual `!tag` command makes sense, but not removing the direct invocation. It does not seem like an improvement to go from `!code` to `/tag get code`, pressing enter, then having to press enter again after it autocompletes to `/tag get codeblock`, all with a bunch of discord UI popping up in the process. Having `/tag` with autocomplete would be useful for finding a tag if you're not sure if exists, but I think we should also keep the faster shorthand.

**Comment by Ibrahim2750mi** [comment] 2023-02-21 20:38
I completely agree with what wookie said, I asked in the discord server but was advised it is a full migration.

Also @wookie184 your review comments makes sense now, sorry for misunderstanding.

**Comment by Robin5605** [comment] 2023-02-22 19:30
I'm also in favor of what wookie said. Seems like a downgrade to remove to !tag functionality. Ideally the slash command would increase visibility

**Comment by mbaruh** [comment] 2023-02-22 19:44
Yeah let's keep the direct usage for now.

**Closed** 2023-02-27 19:29 UTC
Labels: a: tags, t: enhancement, status: approved
