### ISSUE TITLE
Duckpond doesn't work in threads

### ISSUE THREAD

**Issue by Akarys42** [python-discord/bot#1968] opened 2021-11-22 08:15 UTC
Due to how we select the channels inside the duckpond cog, if the channel is a thread the bot cannot find it

https://github.com/python-discord/bot/blob/0cfbac90575098a9f9e0c8ee2ee96d537f0413c4/bot/exts/fun/duck_pond.py#L168-L170

This raises a question though, why are we using `on_raw_reaction_add` and not a normal `on_reaction_add` with all the payload already resolved? I couldn't find the information in #621, maybe @lemonsaurus would remember?

**Comment by TizzySaurus** [comment] 2021-11-22 09:00
@Akarys42 This is a duplicate of #1930.

**Comment by TizzySaurus** [comment] 2021-11-22 09:08
Have copied this into #1930. Will close now as it's a duplicate.

**Closed by TizzySaurus** 2021-11-22 09:08 UTC
Labels: t: bug, p: 3 - low, a: fun
