### ISSUE TITLE
Announce OT name changes when they happen

### ISSUE THREAD

**Issue by fiskenslakt** [python-discord/bot#717] opened 2020-01-04 03:17 UTC
# Abstract

Each day when the off-topic channel names change, the bot will post in that channel announcing what name the channel changed to.

# Specification

The post itself should look something along the lines of:
> Channel name changed to `ot0-channel-name`

## Additional features

Lemon and I thought it might be fun to add some metrics to this post. Namely the of number times this channel name has been picked, and the name's creation date. A possible format for this might look like the following:
> Channel name changed to `ot0-channel-name`. This named has been picked `42` times and was created on `Jan 1st 1970`.

For fun, a possible format in the case where the channel name in question has been picked for the first time could be something like:
> Channel name changed to `ot0-channel-name`. This is the first time this channel has been picked! It was created on `Jan 1st 1970`.

I'm not married to the term "picked" however, or the overall wording in general. So if someone has suggestions for a better way to word it, make a comment on this issue.

## Implementation details

It's worth discussing some of the details associated with adding metrics to this feature. The current random off-topic channel name system has been in place for a while, and thus historic data should be considered. Having all metrics start at 0 would be a last resort, as it would be much more fun to see what the historic metrics already look like.

### Getting historic data for times channel was picked

Since we don't store logs, in order to get historic channel name changes, we need to poll the server audit logs. Thankfully discord supports this in [their API](https://discordapp.com/developers/docs/resources/audit-log), with the relevant discordpy docs [here](https://discordpy.readthedocs.io/en/latest/api.html?highlight=audit#discord.Guild.audit_logs). Of course this part won't be part of the feature itself, as we only want to poll the logs once in order to get historic data so we can store it.

### Getting creation times

This could be a little trickier assuming we don't already store this data. If it turns out that we don't already have this data, the only option might be to have an admin manually search the discord history for when a name was added to the database.

# Rationale

For me, the best argument for adding this feature is to add context to conversations in off-topic channels discussing the current name of the channel. As of right now, if you search the history of off-topic channels, there is no way of knowing what the channel name was at the time unless someone in the conversation history explicitly says what it is. And since the channel names are jokes, if you're reading the channel history and see people joking about whatever the name was at the time, you miss out on the joke!

The other reason I would like to see this feature is for the metrics. The channel names changing randomly everyday makes for some potentially interesting data! And nothing is more fun than looking at data!

# Motivation

A request for this feature was made in the `#meta` channel, but with a different rationale than what I've written above. Many argued against the validity of the original users rationale, and I agree with them. However since I had my own rationale, I decided I wanted the feature regardless and came up with the idea to add metrics after hearing about it.

# Discussion

A few staff members are pretty neutral about adding this feature, with arguments along the lines of it being a useless feature, and potentially a waste of time. These concerns are valid and understandable; there are many more important issues to take care of, and easy issues like these always get picked up first. If you find yourself agreeing with these concerns, or have additional concerns of your own, feel free to voice your opinion in the comments below.

**Comment by sco1** [comment] 2020-01-04 03:39
> As of right now, if you search the history of off-topic channels, there is no way of knowing what the channel name was at the time unless someone in the conversation history explicitly says what it is. And since the channel names are jokes, if you're reading the channel history and see people joking about whatever the name was at the time, you miss out on the joke!

How often is this actually a situation somebody actually finds themselves in?

> The other reason I would like to see this feature is for the metrics. The channel names changing randomly everyday makes for some potentially interesting data! And nothing is more fun than looking at data!

Seems like a duplicate of https://github.com/python-discord/site/issues/309 and not dependent on daily announcements that the OT name has changed. These metrics would be better gathered on the site side anyway, and the distribution question is fairly moot if we go down the road of changing the name selection to be without replacement until the names are exhausted.

**Comment by fiskenslakt** [comment] 2020-01-04 04:27
These are excellent points!

> How often is this actually a situation somebody finds themselves in?

Probably not very much lol. But I personally have been in this situation more than once, as I often like to read channel history; but I'm probably in the minority there. I still think it would be a fun feature though regardless.

In regards to your point about the duplicate and modification of how we select new channel names:
1. I didn't know about that issue, it's a great idea though.
1. I know I wasn't very clear about this in the issue, but I did intend on these metrics being gathered on the site.
1. I agree the distribution metrics would be much less interesting if this change is made. However I'm not totally sure I'd want this change. It definitely makes way more sense to distribute it evenly this way, but part of me kinda likes the pure randomness. More discussion is certainly needed for this issue.

**Comment by MarkKoz** [comment] 2020-03-28 02:44
> I'm not married to the term "picked" however, or the overall wording in general. So if someone has suggestions for a better way to word it, make a comment on this issue.

How about "this is the first time this name has been used".

> Since we don't store logs, in order to get historic channel name changes, we need to poll the server audit logs.

At least from what I can see in the client, logs only go back a couple of months at most.

> Getting creation times

There's no field for it in the model. Also, I believe some data was migrated to postgresql from the old DB we used. There is an [option](https://stackoverflow.com/questions/9488640/how-to-find-out-when-data-was-inserted-to-postgres/49849450) for postgresql to track it, but I don't know if we have it enabled:

> arguments along the lines of it being a useless feature, and potentially a waste of time. 

Yes, I share this sentiment but if someone is keen on working it then I don't mind letting it get merged.

> I agree the distribution metrics would be much less interesting if this change is made. However I'm not totally sure I'd want this change. It definitely makes way more sense to distribute it evenly this way, but part of me kinda likes the pure randomness. More discussion is certainly needed for this issue.

I'm fine with it either way. I don't think that decision is a blocker for this feature though.

**Comment by Den4200** [comment] 2020-10-25 17:05
This doesn't seem particularly relevant anymore. The name changes are already a prominent and well known feature of our off-topic channels.

**Closed by Den4200** 2020-10-25 17:05 UTC
Labels: a: API, p: 3 - low, s: planning, t: feature
