### ISSUE TITLE
Discord.py docs command

### ISSUE THREAD

**Issue by ItzSylex** [python-discord/bot#1042] opened 2020-07-13 06:29 UTC
## **!docs command for discord.py**

I am aware that there are some plans for `discord.py` in the future and I personally think that `!docs` is being used a lot on this channel.
Would it be possible to make a subcommand or a separate command for discord.py documentation and have it search by keywords?

It would make it a lot easier since in some scenarios the command can get quite long, for example instead of doing `!docs discord.ext.commands.CommandOnCooldown.retry_after` we could simply do `!dpy retry_after`.
I know this could cause some issues since the current `!docs` command displays information of the method/attribute, so I was thinking it could be implemented like this:

The command gets called and it shows a couple results based on the keyword passed

![dpy1](https://user-images.githubusercontent.com/42503343/87277177-06bb3e00-c49f-11ea-9524-270e8a936ae2.png)

The author of the command would have to react based on the results, and then all the information would be displayed.

![dpy2](https://user-images.githubusercontent.com/42503343/87277195-0c188880-c49f-11ea-9aa2-e7d63f6a65be.png)

**Comment by Numerlor** [comment] 2020-07-13 12:35
#447 's implementation should also take care of this. I'm slowly working on a rework to make this all possible in #1014

**Comment by ItzSylex** [comment] 2020-07-13 23:18
> #447 's implementation should also take care of this. I'm slowly working on a rework to make this all possible in #1014

Awesome, looking forward to see it. Good luck

**Comment by MarkKoz** [comment] 2020-08-03 19:29
Duplicate of #447

**Closed by MarkKoz** 2020-08-03 19:29 UTC
