### ISSUE TITLE
New feature for the docs command

### ISSUE THREAD

**Issue by Diabolical5777** [python-discord/bot#1724] opened 2021-08-06 14:59 UTC
When you type in an invalid argument for the docs command and it says "No documentation found for the requested symbol.", it also lists down the closest matches to what you type so you can see what the name of the argument is. Or could take this a step further and make the bot list the closest matches with corresponding number beside it to which the user can write the number/react to the emote showing that number and it would show the docs for that argument

**Comment by Xithrius** [comment] 2021-08-06 21:34
I'm interested in this idea. Does anyone else have thoughts?

**Comment by Akarys42** [comment] 2021-08-12 09:17
I agree, if that's feasible with our current infrastructure let's do this!

**Comment by Akarys42** [comment] 2021-08-12 09:23
In fact, duplicate of #447

**Closed by Akarys42** 2021-08-12 09:23 UTC
Labels: a: docs, t: enhancement
