### ISSUE TITLE
Relay Python language news to #python-news

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/bot#890] opened 2020-04-19 14:12 UTC
We'd like to have a new announcement channel added to the Information category, called #python-news. In here, we'd like to have stuff like new PEPs, new Python releases, and major Python event announcements posted automatically.

This can be achieved through listening to various Python mailing lists, and possibly to the python/cpython releases.

## What to do

* The specific mailing lists we want are `python-ideas` and `comp.lang.python.announce`. 
* These can be handled via this API: https://mail.python.org/archives/api/
* Once you have a working version of this in a test environment, you should contact an admin to get the channel created before merging your PR, and to update your config variables with the right ID.

**Comment by jos-b** [comment] 2020-04-19 15:28
This is a duplicate of #834 I believe, which has more context already.

**Comment by ks129** [comment] 2020-04-19 15:50
Can I work with it? ~~I want to do something big in Python bot too 😅 .~~

**Comment by jos-b** [comment] 2020-04-19 16:03
# Implementation details

## New PEPs

For new PEP information, there is an RSS feed available at https://www.python.org/dev/peps/peps.rss/

## Mailing list

Mailing list messages are a little less trivial but still relatively simple to implement.

**Please note that while the mailman API suggests that you can get threads through it a 500 error is returned on big threads. Another approach (detailed below) must be used**.

There is a URL returning recent threads in HTML format: https://mail.python.org/archives/list/python-announce-list@python.org/recent-threads

Each thread looks like this:
```html
<a class="list-group-item list-group-item-action" href="/archives/list/python-announce-list@python.org/thread/U5PV7BEGLL233QK4FKLA2FAAAWMI75DO/">
	...
</a>
```

We need to get the ID from that `<a>` tag, in this case `U5PV7BEGLL233QK4FKLA2FAAAWMI75DO`. This can now be used with the mailman API.

The API URL looks like this: https://mail.python.org/archives/api/list/python-announce-list@python.org/thread/U5PV7BEGLL233QK4FKLA2FAAAWMI75DO/

This API returns the following data which we will need:
- subject
- starting_email
	- sender_name
	- date
	- content (in case we want to post a brief overview in Discord)

We can use the IDs to create a link to the hyperkitty viewer for the mailing list like so: https://mail.python.org/archives/list/python-announce-list@python.org/thread/U5PV7BEGLL233QK4FKLA2FAAAWMI75DO/

We need to keep a record of which threads we have already posted to the channel, using the IDs. This needs to be persistent so we do not post the same threads every time the bot starts.

A list of all mailing lists is available at https://mail.python.org/archives/?count=200, my recommendation is we should start out with:
- python-ideas
- python-announce-list
- pypi-announce

Both the methods above, for PEPs and mailing list, should be polled at an interval of every 10-30 minutes. This is information we need to get immediately so a bit of delay is fine.

**Closed** 2020-05-13 11:12 UTC
Labels: area: information, priority: 2 - normal, status: WIP, type: feature
