### ISSUE TITLE
Uncaught exception when trying to remove pagination of deleted message

### ISSUE THREAD

**Issue by SebastiaanZ** [python-discord/bot#300] opened 2019-02-01 21:28 UTC
When a message with pagination is removed before the bot tries to remove the pagination reactions, an exception will be raised and displayed in channel:

![bot_exception](https://user-images.githubusercontent.com/33516116/52150473-5d003c80-2670-11e9-8989-6158e1f0d1bd.PNG)

To reproduce this, issue the `!tags` command and remove the message before the bot removes the pagination.

Although this will be a rare event, since it needs moderator removal, we probably want to suppress it anyway so it doesn't show up like above in public channels.

**Comment by kraktus** [comment] 2019-10-10 15:23
I think this issued is fixed, or at least I did achieve to reproduce it, either by using `!helps` or `!tags` commands.

**Comment by scragly** [comment] 2019-11-15 14:53
I've verified just now that the bug is still present.

**Comment by MarkKoz** [comment] 2020-03-27 16:58
Duplicate of #770 and fixed in #771.

**Closed** 2020-03-27 16:58 UTC
Labels: area: backend, meta: duplicate, priority: 2 - normal, type: bug
