### ISSUE TITLE
Message filtering did not account for message with only attachments

### ISSUE THREAD

**Issue by ikuyarihS** [python-discord/bot#549] opened 2019-10-23 07:28 UTC
There was a `mute` issued to an user after posting 5 messages with 5 attachments. The bot issued a `mute` and treated accordingly against message spamming behaviour, however in this case there are two problems:
- They were messages with empty message contents, only attachments.
- The attachments were completely deleted, and there is no way to know what they were.

The log of the case looks like this
```
Deleted by: Python#4329
Date: Oct. 23, 2019, 6:54 a.m.
A̷k̴a̴s̵h̶#4646Oct. 23, 2019, 6:54 a.m. | User ID: 330256174098284554
A̷k̴a̴s̵h̶#4646Oct. 23, 2019, 6:54 a.m. | User ID: 330256174098284554
A̷k̴a̴s̵h̶#4646Oct. 23, 2019, 6:54 a.m. | User ID: 330256174098284554
A̷k̴a̴s̵h̶#4646Oct. 23, 2019, 6:54 a.m. | User ID: 330256174098284554
A̷k̴a̴s̵h̶#4646Oct. 23, 2019, 6:54 a.m. | User ID: 330256174098284554
```

The following codes might be of interest:
```py
    """Detects duplicated messages sent by a single user."""
    relevant_messages = tuple(
        msg
        for msg in recent_messages
        if (
            msg.author == last_message.author
            and msg.content == last_message.content
        )
    )

    total_duplicated = len(relevant_messages)

    if total_duplicated > config['max']:
        ...
```
Which is in [duplicates.py](https://github.com/python-discord/bot/blob/master/bot/rules/duplicates.py)

**Comment by Akarys42** [comment] 2019-10-25 11:27
Hi, I would like to work on it please.

**Comment by ikuyarihS** [comment] 2019-10-26 00:25
Assigning @Akarys42 - If you have any question, don't hesitate to post yours in the dev channel.

**Comment by Akarys42** [comment] 2019-10-27 17:59
As far as I can tell, the mute was issued because of the duplicate of message, but if this rule haven't trigger, the attachment rule would have trigger anyway, and my testing shown that attachment trigger first. What do you want me to do?

**Comment by SebastiaanZ** [comment] 2019-10-27 18:11
Yes, the `duplicates` rule was the one that triggered here.

I don't think @ikuyarihS intention is to stop `antispam` from triggering, but rather to make sure we still get the information: What kind of attachments were deleted? I think we could just relay them to the mod-alerts channel to retain them, regardless of the rule that deleted the attachment. I'm not that concerned about a couple of additional messages in that channel, since it's not a "conversation" channel. (Other mods may, though.)

**Comment by Akarys42** [comment] 2019-10-27 18:22
Okay I though @ikuyarihS wanted to stop it from triggering if the images are differents. I can make the link appear on https://admin.pythondiscord.com/ instead if some mods doesn't want it to appear in mod-alert.

I also get an error about the cog trying to delete the same message twice that I will probably try to investigate.

**Comment by SebastiaanZ** [comment] 2019-10-27 19:19
That's an interesting idea. Since we're only allowing image attachments anyway, we could upload the attachment links and display the images directly in the front-end, Just like regular content or embeds.

**Comment by Akarys42** [comment] 2019-10-28 17:37
Done in python-discord/site#303.

**Closed** 2020-01-13 20:14 UTC
Labels: area: API, area: filters, good first issue, priority: 3 - low, status: WIP, type: bug
