### ISSUE TITLE
Make error embeds more consistent

### ISSUE THREAD

**Issue by D0rs4n** [python-discord/bot#1718] opened 2021-08-04 12:30 UTC
_Currently_, when the bot encounters an error, it sends an error embed containing the error itself, and another embed containing the help for the current command.

To make this consistent, I think we should put those two into one single embed. Like in **[Sir-Lancebot](https://github.com/python-discord/sir-lancebot/blob/c3c5039b71de79dd52f1e617881c9781bc809eef/bot/exts/evergreen/error_handler.py#L75)**:

![alt text](https://cdn.discordapp.com/attachments/635950537262759947/872403296252473395/Kepernyofoto_2021-08-04_-_10.57.20.png)

**Comment by MarkKoz** [comment] 2021-08-04 15:49
Duplicate of #126

**Closed by MarkKoz** 2021-08-04 15:49 UTC
