### ISSUE TITLE
Bulk Deleted messages doesn't appear in #message-change-log

### ISSUE THREAD

**Issue by Akarys42** [python-discord/bot#1381] opened 2021-01-24 16:22 UTC
Currently, we only create an embed when a message is deleted through a single deletion event. Bulk deletions are ignored, which cause messages cleared by a purge-ban to not appear here, which is pretty problematic.

Note that the `!clean` command does trigger a bulk deletion, but we don't want it to appear in the change-log since we already have another logging method for them. We need to come up with a system to ignore those.

**Comment by Xithrius** [comment] 2021-02-03 10:30
WEE WOO WEE WOO IT'S A DUPE OF #150

**Closed by Xithrius** 2021-02-03 10:30 UTC
Labels: a: moderation, p: 1 - high, t: bug
